services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credito-frontend
    ports:
      - "80:80"
    environment:
      # Environment variables for the frontend if needed
      API_URL: http://backend:8080
    networks:
      - credito-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  credito-network:
    driver: bridge